### ISSUE TITLE
quarkus properties broken fully in vscode

### ISSUE THREAD

**Issue by maxandersen** [xorye/vscode-quarkus#638] opened 2024-01-26 13:17 UTC
i type in quarkus properties files there is no longer any content assist.

I can see in error log the following:

```
Jan 26, 2024 2:15:09 PM org.eclipse.lsp4mp.jdt.core.PropertiesManager getMicroProfileProjectInfo
INFO: Start computing MicroProfile properties for '/Users/manderse/code/quarkusio/quarkus-zulip-bot' project.
Jan 26, 2024 2:15:09 PM org.eclipse.lsp4mp.jdt.core.PropertiesManager getMicroProfileProjectInfo
INFO: End computing MicroProfile properties for '/Users/manderse/code/quarkusio/quarkus-zulip-bot' project in 570ms.
[Error - 2:15:09 PM] 26 Jan 2024, 14.15.09 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
java.lang.Exception: java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.getMicroProfileProjectInfo(MicroProfileDelegateCommandHandler.java:125)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.executeCommand(MicroProfileDelegateCommandHandler.java:58)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:616)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.JDTUtilsLSImpl.getJavadoc(JDTUtilsLSImpl.java:134)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.collectProperties(QuarkusKubernetesProvider.java:153)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.processClass(QuarkusKubernetesProvider.java:110)
	at org.eclipse.lsp4mp.jdt.core.AbstractTypeDeclarationPropertiesProvider.collectProperties(AbstractTypeDeclarationPropertiesProvider.java:58)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.collectProperties(PropertiesManager.java:261)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager$1.acceptSearchMatch(PropertiesManager.java:237)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2206)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3169)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2887)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2059)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1370)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1407)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1527)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.scanJavaClasses(PropertiesManager.java:221)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:145)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:113)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:104)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.lambda$0(MicroProfileDelegateCommandHandler.java:110)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.javadoc.JavadocContentAccess cannot be found by org.eclipse.lsp4mp.jdt.core_0.10.0.20231005-1519
	... 24 more

[Error - 2:15:09 PM] 26 Jan 2024, 14.15.09 An internal error occurred during: "MicroProfile properties collector".
org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.JDTUtilsLSImpl.getJavadoc(JDTUtilsLSImpl.java:134)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.collectProperties(QuarkusKubernetesProvider.java:153)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.processClass(QuarkusKubernetesProvider.java:110)
	at org.eclipse.lsp4mp.jdt.core.AbstractTypeDeclarationPropertiesProvider.collectProperties(AbstractTypeDeclarationPropertiesProvider.java:58)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.collectProperties(PropertiesManager.java:261)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager$1.acceptSearchMatch(PropertiesManager.java:237)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2206)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3169)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2887)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2059)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1370)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1407)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1527)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.scanJavaClasses(PropertiesManager.java:221)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:145)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:113)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:104)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.lambda$0(MicroProfileDelegateCommandHandler.java:110)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.javadoc.JavadocContentAccess cannot be found by org.eclipse.lsp4mp.jdt.core_0.10.0.20231005-1519
	... 24 more

[Error - 2:15:09 PM] 26 Jan 2024, 14.15.09 Error in calling delegate command handler
java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
java.lang.Exception: java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.getMicroProfileProjectInfo(MicroProfileDelegateCommandHandler.java:125)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.executeCommand(MicroProfileDelegateCommandHandler.java:58)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:616)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.JDTUtilsLSImpl.getJavadoc(JDTUtilsLSImpl.java:134)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.collectProperties(QuarkusKubernetesProvider.java:153)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.processClass(QuarkusKubernetesProvider.java:110)
	at org.eclipse.lsp4mp.jdt.core.AbstractTypeDeclarationPropertiesProvider.collectProperties(AbstractTypeDeclarationPropertiesProvider.java:58)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.collectProperties(PropertiesManager.java:261)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager$1.acceptSearchMatch(PropertiesManager.java:237)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2206)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3169)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2887)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2059)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1370)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1407)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1527)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.scanJavaClasses(PropertiesManager.java:221)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:145)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:113)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:104)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.lambda$0(MicroProfileDelegateCommandHandler.java:110)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.javadoc.JavadocContentAccess cannot be found by org.eclipse.lsp4mp.jdt.core_0.10.0.20231005-1519
	... 24 more

Jan 26, 2024 2:15:10 PM org.eclipse.lsp4mp.jdt.core.PropertiesManager getMicroProfileProjectInfo
INFO: Start computing MicroProfile properties for '/Users/manderse/code/quarkusio/quarkus-zulip-bot' project.
Jan 26, 2024 2:15:10 PM org.eclipse.lsp4mp.jdt.core.PropertiesManager getMicroProfileProjectInfo
INFO: End computing MicroProfile properties for '/Users/manderse/code/quarkusio/quarkus-zulip-bot' project in 300ms.
[Error - 2:15:10 PM] 26 Jan 2024, 14.15.10 An internal error occurred during: "MicroProfile properties collector".
org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.JDTUtilsLSImpl.getJavadoc(JDTUtilsLSImpl.java:134)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.collectProperties(QuarkusKubernetesProvider.java:153)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.processClass(QuarkusKubernetesProvider.java:110)
	at org.eclipse.lsp4mp.jdt.core.AbstractTypeDeclarationPropertiesProvider.collectProperties(AbstractTypeDeclarationPropertiesProvider.java:58)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.collectProperties(PropertiesManager.java:261)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager$1.acceptSearchMatch(PropertiesManager.java:237)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2206)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3169)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2887)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2059)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1370)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1407)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1527)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.scanJavaClasses(PropertiesManager.java:221)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:145)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:113)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:104)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.lambda$0(MicroProfileDelegateCommandHandler.java:110)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.javadoc.JavadocContentAccess cannot be found by org.eclipse.lsp4mp.jdt.core_0.10.0.20231005-1519
	... 24 more

[Error - 2:15:10 PM] 26 Jan 2024, 14.15.10 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
java.lang.Exception: java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.getMicroProfileProjectInfo(MicroProfileDelegateCommandHandler.java:125)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.executeCommand(MicroProfileDelegateCommandHandler.java:58)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:616)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.JDTUtilsLSImpl.getJavadoc(JDTUtilsLSImpl.java:134)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.collectProperties(QuarkusKubernetesProvider.java:153)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.processClass(QuarkusKubernetesProvider.java:110)
	at org.eclipse.lsp4mp.jdt.core.AbstractTypeDeclarationPropertiesProvider.collectProperties(AbstractTypeDeclarationPropertiesProvider.java:58)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.collectProperties(PropertiesManager.java:261)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager$1.acceptSearchMatch(PropertiesManager.java:237)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2206)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3169)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2887)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2059)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1370)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1407)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1527)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.scanJavaClasses(PropertiesManager.java:221)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:145)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:113)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:104)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.lambda$0(MicroProfileDelegateCommandHandler.java:110)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.javadoc.JavadocContentAccess cannot be found by org.eclipse.lsp4mp.jdt.core_0.10.0.20231005-1519
	... 24 more

[Error - 2:15:10 PM] 26 Jan 2024, 14.15.10 Error in calling delegate command handler
java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
java.lang.Exception: java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.getMicroProfileProjectInfo(MicroProfileDelegateCommandHandler.java:125)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.executeCommand(MicroProfileDelegateCommandHandler.java:58)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:616)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jdt/ls/core/internal/javadoc/JavadocContentAccess
	at org.eclipse.lsp4mp.jdt.internal.core.ls.JDTUtilsLSImpl.getJavadoc(JDTUtilsLSImpl.java:134)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.collectProperties(QuarkusKubernetesProvider.java:153)
	at com.redhat.microprofile.jdt.internal.quarkus.kubernetes.properties.QuarkusKubernetesProvider.processClass(QuarkusKubernetesProvider.java:110)
	at org.eclipse.lsp4mp.jdt.core.AbstractTypeDeclarationPropertiesProvider.collectProperties(AbstractTypeDeclarationPropertiesProvider.java:58)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.collectProperties(PropertiesManager.java:261)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager$1.acceptSearchMatch(PropertiesManager.java:237)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2206)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3169)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2887)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2059)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1370)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1407)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1527)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:254)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:600)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:669)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.scanJavaClasses(PropertiesManager.java:221)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:145)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:113)
	at org.eclipse.lsp4mp.jdt.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:104)
	at org.eclipse.lsp4mp.jdt.internal.core.ls.MicroProfileDelegateCommandHandler.lambda$0(MicroProfileDelegateCommandHandler.java:110)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.javadoc.JavadocContentAccess cannot be found by org.eclipse.lsp4mp.jdt.core_0.10.0.20231005-1519
	... 24 more
```

running v1.16.0 Preview or 1.17 prerelease both errors.

**Comment by fbricon** [comment] 2024-01-26 13:19
this is caused by some recent refactorings in jdt.ls. We need to update quarkus-ls to adapt to those changes.

**Comment by fbricon** [comment] 2024-01-26 13:48
there are issues in lsp4mp and qute.jdt, I'll open PRs to fix them and trigger a pre-release once they're merged

**Closed as completed** 2024-01-26 18:17 UTC
Labels: bug

**Comment by danieloh30** [comment] 2024-01-26 23:36
@angelozerr how can I fix this in my local VS Code?

**Comment by fbricon** [comment] 2024-01-27 09:27
@danieloh30 try installing the vscode microprofile pre-release build from the marketplace

**Comment by danieloh30** [comment] 2024-01-27 13:18
@fbricon As I mentioned, I'm using the latest pre-release for Quarkus tools, MicroProfile tool, and Java support but it doesn't work for me. Are you saying there was a new release in 3 hrs ago?

**Comment by danieloh30** [comment] 2024-01-27 13:22
Cool. it works now. But the error still shows in the output
<img width="1079" alt="image" src="https://github.com/redhat-developer/vscode-quarkus/assets/14066977/ca5c029a-34c9-42ed-a5cd-07610bd5c3f7">

**Comment by fbricon** [comment] 2024-01-27 23:26
@danieloh30 you're seeing a different, unrelated problem, please open a new ticket for that one

**Comment by danieloh30** [comment] 2024-01-28 04:39
Sure! FYI https://github.com/redhat-developer/vscode-microprofile/issues/178
