### ISSUE TITLE
Wrong `java` used while `JaveSE-17` is configured

### ISSUE THREAD

**Issue by tigerinus** [xorye/vscode-quarkus#495] opened 2022-04-19 21:36 UTC
For work reason I have both JDK1.8 and JDK17 (`mandrel-java17`) installed. The `JAVA_HOME` points to JDK1.8 path.

However in the VSCode workspace setting (`.vscode/settings.json`), I have

```json
{
    "java.configuration.updateBuildConfiguration": "automatic",
    "java.jdt.ls.java.home": "~/.local/mandrel-java17",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-17",
            "path": "~/.local/mandrel-java17",
            "default": true
        }
    ],
}
```

When trying to debug the Quarkus app within vscode I still get

```
Caused by: java.lang.UnsupportedClassVersionError: io/quarkus/maven/components/BootstrapSessionListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Please help.

**Comment by rgrunber** [comment] 2022-04-29 14:20
We had a very similar bug from a few days earlier, https://github.com/redhat-developer/vscode-java/issues/2421 . Also filed against Quarkus which I moved to vscode-java.

I'll try again to reproduce this.

**Comment by rgrunber** [comment] 2022-04-30 04:24
Ok, so looks like your project was compiled with Java 11 (55.0) but Java 1.8 (52.0) is being used to run the project (since you set it as `JAVA_HOME`).

If you want to try with Java 1.8, you could look at the Quarkus project build files (Maven or Gradle) and change the compiler source/target to 1.8 to get everything building. However, I think recent versions of Quarkus require Java 11 at a minimum.

Alternatively, you could try setting `JAVA_HOME=~/.local/mandrel-java17`. That should ensure that your project, which is compiled as Java 11 uses a runtime (Java 17) that should be compatible.

**Comment by angelozerr** [comment] 2024-08-22 12:42
I close this issue since @rgrunber give a great explanation.

@tigerinus if you have again problem, please reopen it.

**Closed as completed by angelozerr** 2024-08-22 12:42 UTC
Labels: bug, question
